[package]
name = "termiku"
version = "0.1.0"
authors = ["ShinySaana", "LunarLambda"]
edition = "2018"

[dependencies]
libc = "0.2.62"
mio = "0.6"
mio-extras = "2.0.5"
glium = "0.26.0-alpha3"
image = "0.22.2"
arrayvec = "0.5.0"

[dependencies.rusttype]
version = "0.8.1"
features = ["gpu_cache"]
